// Regenerate src/words.ts from two public lists. Run: pnpm --filter @wordy/rules words
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const GUESS_SRC = 'https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt'
const ANSWER_SRC = 'https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-usa-no-swears-medium.txt'

const five = (text) => text.split(/\r?\n/).map((w) => w.trim().toLowerCase()).filter((w) => /^[a-z]{5}$/.test(w))

const guessText = await (await fetch(GUESS_SRC)).text()
const answerText = await (await fetch(ANSWER_SRC)).text()
const guesses = new Set(five(guessText))
const answers = [...new Set(five(answerText))].filter((w) => guesses.has(w)).sort()
for (const a of answers) guesses.add(a)

const out = `// Generated by scripts/build-words.mjs. Do not edit by hand.
// Answers: common five-letter words from first20hours/google-10000-english (Google Trillion Word Corpus, public data).
// Guesses: five-letter words from dwyl/english-words (Unlicense), plus every answer.

/** The words a round can ask for. Never sent to a client. */
export const ANSWERS: readonly string[] = ${JSON.stringify(answers)}

const GUESS_WORDS: readonly string[] = ${JSON.stringify([...guesses].sort())}

/** Every word a player may submit. */
export const GUESSES: ReadonlySet<string> = new Set(GUESS_WORDS)

export function isWord(word: string): boolean {
  return GUESSES.has(word.toLowerCase())
}
`
const here = dirname(fileURLToPath(import.meta.url))
writeFileSync(join(here, '..', 'src', 'words.ts'), out)
console.log(`answers ${answers.length}, guesses ${guesses.size}`)
