// Regenerate src/words.ts from two public lists. Run: pnpm --filter @wordy/rules words
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const GUESS_SRC = 'https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt'
// The curated Wordle answer list (2,315 common words, no names or places), as mirrored on GitHub.
const ANSWER_SRC = 'https://gist.githubusercontent.com/cfreshman/a03ef2cba789d8cf00c08f767e0fad7b/raw/wordle-answers-alphabetical.txt'

// Common-word floor: Zipf frequency from data/answer-zipf.json (see scripts/answer-zipf.py).
// 3.0 keeps about 1,700 of the 2,315 curated answers and drops the tail (abled, axion, eking).
const ZIPF_FLOOR = 3.0
// Real words that read as first names on a scoreboard. Frequency cannot catch these; a name is common.
const NAME_FIRST = new Set(['billy', 'bobby', 'carol', 'daisy', 'harry', 'heath', 'holly', 'lance', 'patty', 'ralph', 'randy', 'roger', 'sally', 'sandy'])

const five = (text) => text.split(/\r?\n/).map((w) => w.trim().toLowerCase()).filter((w) => /^[a-z]{5}$/.test(w))

const guessText = await (await fetch(GUESS_SRC)).text()
const answerText = await (await fetch(ANSWER_SRC)).text()
const guesses = new Set(five(guessText))
const here = dirname(fileURLToPath(import.meta.url))
const zipf = JSON.parse(readFileSync(join(here, '..', 'data', 'answer-zipf.json'), 'utf8'))
const curated = [...new Set(five(answerText))].sort()
for (const a of curated) guesses.add(a)
const answers = curated.filter((w) => (zipf[w] ?? 0) >= ZIPF_FLOOR && !NAME_FIRST.has(w))

const out = `// Generated by scripts/build-words.mjs. Do not edit by hand.
// Answers: the curated Wordle answer list, kept to its common part (Zipf >= ${ZIPF_FLOOR}) minus name-first words.
// Guesses: five-letter words from dwyl/english-words (Unlicense), plus every answer.

/** The words a round can ask for. Never sent to a client. */
export const ANSWERS: readonly string[] = ${JSON.stringify(answers)}

const GUESS_WORDS: readonly string[] = ${JSON.stringify([...guesses].sort())}

/** Every word a player may submit. */
export const GUESSES: ReadonlySet<string> = new Set(GUESS_WORDS)

export function isWord(word: string): boolean {
  return GUESSES.has(word.toLowerCase())
}
`
writeFileSync(join(here, '..', 'src', 'words.ts'), out)
console.log(`answers ${answers.length} of ${curated.length} curated, guesses ${guesses.size}`)
